#!/usr/bin/env python3
"""PreToolUse hook (matcher: Edit|Write|MultiEdit), MID severity. This
codebase doesn't have a `src/generated*` directory, but it has the same
shape of risk: `_LEARNED_LUT`/`_LEARNED_LUT_V2` numpy array literals in
`brands/*_learned.py` are measurement output from `tools/fit_final_lut.py`
(raw+jpeg pairs -> per-bin averages -> PAVA smoothing), not hand-tuned
constants. Hand-editing the array numbers directly would silently
desync the shipped LUT from anything the fitting pipeline could
reproduce or re-verify - the exact failure mode "generated file, don't
hand-edit" guards against elsewhere.

MID severity: `ask()` - falls through to Claude Code's normal permission
prompt rather than an automatic allow/deny, since sometimes a small
hand-correction genuinely is the intended fix (this session's own PAVA
non-monotonic-cliff correction was a full regeneration, but a one-value
typo fix might not warrant re-running a 2-hour fit)."""
import ast
import json
import os
import re
import sys

from _hook_common import ask, allow

HOOK_NAME = "protect_generated_files"
SEVERITY = "MID"

_LEARNED_LUT_FILE_RE = re.compile(r"(^|/)brands/[^/]*_learned\.py$")
_LUT_ASSIGN_NAME_RE = re.compile(r"^_LEARNED_LUT\w*$")


def read_input():
    return json.load(sys.stdin)


def normalize(path):
    return (path or "").replace(os.sep, "/")


def is_learned_brand_file(path):
    return bool(_LEARNED_LUT_FILE_RE.search(normalize(path)))


def lut_array_ranges(file_path):
    """Returns [(name, start_line, end_line), ...] for every module-level
    `_LEARNED_LUT*= np.array([...])` assignment, or None if unparseable."""
    if not os.path.exists(file_path):
        return []
    try:
        with open(file_path, encoding="utf-8") as f:
            tree = ast.parse(f.read())
    except Exception:
        return None
    ranges = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name) and _LUT_ASSIGN_NAME_RE.match(t.id):
                    end = getattr(node, "end_lineno", node.lineno)
                    ranges.append((t.id, node.lineno, end))
    return ranges


def line_of_offset(text, offset):
    return text.count("\n", 0, offset) + 1


def touched_lut_array(file_path, old_string):
    if not old_string or not os.path.exists(file_path):
        return None
    with open(file_path, encoding="utf-8") as f:
        text = f.read()
    ranges = lut_array_ranges(file_path)
    if not ranges:
        return None
    idx = text.find(old_string)
    if idx == -1:
        return None
    start_line = line_of_offset(text, idx)
    end_line = line_of_offset(text, idx + len(old_string))
    for name, s, e in ranges:
        if start_line <= e and end_line >= s:
            return name
    return None


def main():
    data = read_input()
    tool = data.get("tool_name")
    if tool not in ("Edit", "Write", "MultiEdit"):
        allow()
        return
    ti = data.get("tool_input") or {}
    file_path = ti.get("file_path", "")
    if not file_path or not is_learned_brand_file(file_path):
        allow()
        return

    if tool == "Write":
        # Overwriting the whole file could plausibly rewrite the LUT too -
        # can't tell from a Write call alone, so ask rather than guess.
        ask(
            f"{file_path} contains a _LEARNED_LUT array generated by "
            "tools/fit_final_lut.py - a Write overwrites the whole file, "
            "which may include hand-editing that array instead of "
            "regenerating it. Confirm this isn't a hand-edit of the LUT "
            "values, or regenerate via tools/fit_final_lut.py instead."
        )
        return

    if tool == "MultiEdit":
        edits = ti.get("edits") or []
    else:
        edits = [{"old_string": ti.get("old_string", "")}]

    for e in edits:
        name = touched_lut_array(file_path, e.get("old_string", ""))
        if name:
            ask(
                f"This edit touches `{name}` in {file_path}, a numpy array "
                "generated by tools/fit_final_lut.py (raw+jpeg fitting + "
                "PAVA smoothing), not a hand-tuned constant. Hand-editing "
                "the numbers desyncs the shipped LUT from anything the "
                "fitting pipeline could reproduce. Confirm this is "
                "intentional (e.g. reverting to a re-generated array), or "
                "re-run tools/fit_final_lut.py instead."
            )
            return

    allow()


if __name__ == "__main__":
    main()
