#!/usr/bin/env python3
"""PreToolUse hook (matcher: Edit|Write|MultiEdit), MEDIUM severity. This
codebase doesn't have a `src/generated*` directory, but it has the same
shape of risk: `_LEARNED_LUT`/`_LEARNED_LUT_V2` numpy array literals in
`brands/*_learned.py` are measurement output from `tools/fit_final_lut.py`
(raw+jpeg pairs -> per-bin averages -> PAVA smoothing), not hand-tuned
constants. Hand-editing the array numbers directly would silently
desync the shipped LUT from anything the fitting pipeline could
reproduce or re-verify - the exact failure mode "generated file, don't
hand-edit" guards against elsewhere.

MEDIUM severity: deny + sentinel override, not a hard block, since sometimes
a small hand-correction genuinely is the intended fix (this session's own
PAVA non-monotonic-cliff correction was a full regeneration, but a
one-value typo fix might not warrant re-running a 2-hour fit).

**정정(2026-08-15)**: 원래 `ask()`를 썼는데, subagent 디스패치로 실측한
결과 subagent의 Edit 콜에서는 `ask()`가 프롬프트 없이 조용히 통과됨
(subagent 컨텍스트엔 프롬프트를 띄울 화면이 없어서로 추정). 이
프로젝트는 Controller가 subagent를 디스패치해서 실제 작업을 시키는
워크플로우라 `ask()`는 정확히 그 경우에 보호 기능이 0. deny + sentinel
override로 바꿔서 orchestrator/subagent 둘 다 동일하게 동작하게 함."""
import ast
import json
import os
import re
import sys

from _hook_common import (allow, allow_with_medium_approval, allow_with_override,
                           deny, medium_approval, sentinel_override, write_pending_caution)

HOOK_NAME = "protect_generated_files"
SEVERITY = "MEDIUM"

_LEARNED_LUT_FILE_RE = re.compile(r"(^|/)brands/[^/]*_learned\.py$")
_LUT_ASSIGN_NAME_RE = re.compile(r"^_LEARNED_LUT\w*$")


def read_input():
    return json.load(sys.stdin)


def normalize(path):
    return (path or "").replace(os.sep, "/")


def is_learned_brand_file(path):
    return bool(_LEARNED_LUT_FILE_RE.search(normalize(path)))


def lut_array_ranges(file_path):
    """Returns [(name, start_line, end_line), ...] for every module-level
    `_LEARNED_LUT*= np.array([...])` assignment, or None if unparseable."""
    if not os.path.exists(file_path):
        return []
    try:
        with open(file_path, encoding="utf-8") as f:
            tree = ast.parse(f.read())
    except Exception:
        return None
    ranges = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name) and _LUT_ASSIGN_NAME_RE.match(t.id):
                    end = getattr(node, "end_lineno", node.lineno)
                    ranges.append((t.id, node.lineno, end))
    return ranges


def line_of_offset(text, offset):
    return text.count("\n", 0, offset) + 1


def touched_lut_array(file_path, old_string):
    if not old_string or not os.path.exists(file_path):
        return None
    with open(file_path, encoding="utf-8") as f:
        text = f.read()
    ranges = lut_array_ranges(file_path)
    if not ranges:
        return None
    idx = text.find(old_string)
    if idx == -1:
        return None
    start_line = line_of_offset(text, idx)
    end_line = line_of_offset(text, idx + len(old_string))
    for name, s, e in ranges:
        if start_line <= e and end_line >= s:
            return name
    return None


def _deny_or_override(target, reason, tool_use_id=None):
    override_reason = sentinel_override(HOOK_NAME, target)
    if override_reason:
        allow_with_override(HOOK_NAME, SEVERITY, HOOK_NAME, target, override_reason)
        return
    caution = medium_approval(HOOK_NAME, target)
    if caution is not None:
        write_pending_caution(tool_use_id, caution)
        allow_with_medium_approval(HOOK_NAME, SEVERITY, HOOK_NAME, target, caution)
        return
    deny(
        HOOK_NAME,
        f"{reason} To override: write .claude/hooks/.pending_override.json "
        f'with {{"rule": "{HOOK_NAME}", "target": "{target}", "reason": '
        '"<reason>", "timestamp": <time.time()>}, then retry immediately. '
        "Or: dispatch an opus Agent whose response contains "
        f'"MEDIUM-APPROVE: {HOOK_NAME} :: {target} :: <caution>" - the '
        "next matching call will be let through with that caution "
        "delivered back to you.",
        severity=SEVERITY,
    )


def main():
    data = read_input()
    tool = data.get("tool_name")
    if tool not in ("Edit", "Write", "MultiEdit"):
        allow()
        return
    ti = data.get("tool_input") or {}
    file_path = ti.get("file_path", "")
    tool_use_id = data.get("tool_use_id")
    if not file_path or not is_learned_brand_file(file_path):
        allow()
        return

    if tool == "Write":
        # Overwriting the whole file could plausibly rewrite the LUT too -
        # can't tell from a Write call alone, so flag rather than guess.
        _deny_or_override(
            file_path,
            f"{file_path} contains a _LEARNED_LUT array generated by "
            "tools/fit_final_lut.py - a Write overwrites the whole file, "
            "which may include hand-editing that array instead of "
            "regenerating it. Confirm this isn't a hand-edit of the LUT "
            "values, or regenerate via tools/fit_final_lut.py instead.",
            tool_use_id=tool_use_id,
        )
        return

    if tool == "MultiEdit":
        edits = ti.get("edits") or []
    else:
        edits = [{"old_string": ti.get("old_string", "")}]

    for e in edits:
        name = touched_lut_array(file_path, e.get("old_string", ""))
        if name:
            _deny_or_override(
                file_path,
                f"This edit touches `{name}` in {file_path}, a numpy array "
                "generated by tools/fit_final_lut.py (raw+jpeg fitting + "
                "PAVA smoothing), not a hand-tuned constant. Hand-editing "
                "the numbers desyncs the shipped LUT from anything the "
                "fitting pipeline could reproduce. Confirm this is "
                "intentional (e.g. reverting to a re-generated array), or "
                "re-run tools/fit_final_lut.py instead.",
                tool_use_id=tool_use_id,
            )
            return

    allow()


if __name__ == "__main__":
    main()
